name:                homework-III-IV
version:             0.1.0.0
github:              "ABGEO07/paradigms-hw-3-4"
license:             MIT
author:              "Temuri Takalandze"
maintainer:          "me@abgeo.dev"
copyright:           "2020 ABGEO"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         CST Programming Paradigms - Homework 3 and 4

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  homework-III-IV-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework-III-IV

tests:
  homework-III-IV-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework-III-IV
